# Generated by Django 3.2.9 on 2021-11-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('people_in_room', models.IntegerField()),
            ],
        ),
    ]
